/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Theme variables mapping
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        primary: "var(--color-primary)",
        accent: "var(--color-accent)",
        charcoal: "var(--color-charcoal)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        danger: "var(--color-danger)",
        
        // Static Design V2 specific colors
        "inverse-primary": "#585990",
        "surface-container-high": "#292932",
        "outline": "#918f9a",
        "on-secondary-fixed-variant": "#005236",
        "on-surface": "#e5e1e7",
        "error": "#ffb4ab",
        "secondary": "#4edea3",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-error": "#690005",
        "on-background": "#e5e1e7",
        "status-success": "#34d399",
        "tertiary": "#e1dfff",
        "on-primary-container": "#4b4d83",
        "surface-variant": "#353438",
        "on-surface-variant": "#c7c4d7",
        "surface-container-lowest": "#0e0e11",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1b1b23",
        "on-secondary-fixed": "#002114",
        "inverse-surface": "#e5e1e7",
        "terminal-black": "#000000",
        "outline-variant": "#46464f",
        "on-secondary-container": "#003e28",
        "secondary-fixed": "#6ffbbe",
        "on-secondary": "#003824",
        "error-container": "#93000a",
        "surface": "#131317",
        "secondary-container": "#00b47d",
        "surface-dim": "#13131b",
        "status-error": "#ff5f56",
        "surface-container": "#201f23",
        "tertiary-fixed-dim": "#c0c1ff",
        "inverse-on-surface": "#313034",
        "on-tertiary-container": "#3c3cca",
        "on-primary": "#292b5e",
        "surface-container-highest": "#353438",
        "primary-fixed-dim": "#c0c1ff",
        "tertiary-container": "#c0c1ff",
        "on-primary-fixed-variant": "#404176",
        "on-primary-fixed": "#131449",
        "surface-tint": "#c0c1ff",
        "surface-bright": "#39393d",
        "primary-fixed": "#e1e0ff",
        "primary-container": "#c0c1ff",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary": "#1000a9",
        "tertiary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#07006c",
      },
      spacing: {
        "container-max": "1280px",
        "nav-height": "56px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px",
        "announcement-height": "32px",
      },
      fontFamily: {
        "body-sm": ["Geist"],
        "body-base": ["Geist"],
        "headline-md": ["Geist"],
        "code-label": ["JetBrains Mono"],
        "display-lg-mobile": ["Geist"],
        "display-lg": ["Geist"],
        "log-tiny": ["JetBrains Mono"],
      },
      boxShadow: {
        premium: "0 12px 30px rgba(0,0,0,0.02)",
      },
    },
  },
  plugins: [],
}
