blank_issues_enabled: true
contact_links:
  - name: FlientSec Discussions
    url: https://github.com/Rarebuffalo/Flientsec/discussions
    about: Ask questions, align on rules setups, and share custom policies templates.
